### ISSUE TITLE
Cluster setup and testing

### ISSUE THREAD

**Issue by mtchavez** [mtchavez/ansible-influxdb#6]
- [ ] Set up a cluster using the role
- [ ] Test the cluster comes up correctly
- [ ] Cluster using Vagrant for testing

**Comment by johnjelinek** [comment]
Clustering works pretty good:

```
---
- name: Provision InfluxDB
# ========================
  hosts: influx
  gather_facts: yes

  roles:
  - { role: mtchavez.influxdb,
      influxdb_hostname: "{{ ansible_hostname }}",
      influxdb_influxd_opts: "-join {{ groups['influx'] | portify(influxdb_bind_address) | join(',') }}" }
```

Here's `filter_plugins/portify.py`:

```
def portify(arg, suffix):
    return map(lambda x: x + suffix, arg)


class FilterModule(object):

    def filters(self):
        return {'portify': portify}
```

**Comment by mtchavez** [comment]
Putting this on hold due to [this blog post](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) outlining the intentions to make clustering a closed source feature.

**Comment by mtchavez** [comment]
Closing out
